### ISSUE TITLE
Preclinical use

### ISSUE THREAD

**Issue by MariaICL** [davidssmith/DCEMRI.jl#26]
Hi,
I would like to use this software to analyse preclinical DCE data, where I don't have the data regarding Cp (Arterial input function), so a different model would be required. Is this possible?
Thanks,

Maria.

**Comment by davidssmith** [comment]
Yes, another model could be used but it would need to be programmed in. To do this, you could add a function to `src/models.jl`, and then add a case around line 86 in `src/science.jl` to call it when the `models` array contains 4.

Or if you can obtain or approximate an AIF, it can be used instead of the example AIF provided by passing it into the input MAT file.
